name: Mypy Workflow

on: [push]

jobs:
  mypy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Python environment
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        
    - name: Install mypy
      run: pip install mypy
      
    - name: Run mypy on repository
      run: mypy .
